repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        name: merge conflict protection
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        name: commit message enforcement
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: tflint
        name: terraform linting
        stages: [commit]
        entry: make tf-lint
        language: system
  - repo: local
    hooks:
      - id: terraform-docs
        name: terraform documentation
        stages: [commit]
        entry: make tf-docs
        language: system
  - repo: local
    hooks:
      - id: security-scan
        name: security scanning
        stages: [commit]
        entry: make sec-scan
        language: system
